author: guzhen1989 # 作者
description: guzhen's blog
keyword: hexo-theme, vuejs
favicon: 

excerpt_link: 阅读全文

menu:
 Home: /
 Tags: /tags/
 Archives: /archives/
 Projects: /project/
 About: /about/

# highlight
highlight:
  tomorrow

# catalog
catalog: true

# donate
donate: true

# comment
# you can set gitment or uyan

comment: uyan

# gitment config
#gitment_owner: guzhen
#gitment_repo: guzhen1989.github.io
#gitment_oauth_id:
#gitment_oauth_secret:

# uyan
# if you want to use uyan as your blog comment, plz remove/comment out gitment config

baidu_id: 

about: 
  banner: http://file.muyutech.com/about.jpg
  avatar: /css/images/avatar.jpg
  description: 动漫 and 小说 and 技术！！ 好吧，先走出第一步吧
  # Links
  weibo_username:
  twitter_username:
  github_username: guzhen1989
  zhihu_username: guzhen1989
  douban_username:
  gitee_username: 1132053388